/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.TopLevelRole_Engineering;

import Business.EcoSystem;
import Business.Entities.SalesData;
import java.awt.CardLayout;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import userinterface.SalesExecutiveRole_Engineering.ReviewReportPanel;
import userinterface.TopLevelRole_Chemicals.ResultChemicalsPanel;

/**
 *
 * @author msneh
 */
public class ResultEngineeringPanel extends javax.swing.JPanel {

   private JPanel userProcessContainer;
   private EcoSystem ecosystem;
    public ResultEngineeringPanel(JPanel userProcessContainer,EcoSystem ecosystem) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.ecosystem=ecosystem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        importSalesReportButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        salesReportTable = new javax.swing.JTable();
        showHistogramButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        yearOneTextField = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        profitOneTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        yearTwoTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        profitTwoTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        yearThreeTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        profitThreeTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 204, 255));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 51, 255), 2, true));
        setForeground(new java.awt.Color(102, 51, 255));

        importSalesReportButton.setBackground(new java.awt.Color(153, 204, 255));
        importSalesReportButton.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        importSalesReportButton.setForeground(new java.awt.Color(102, 51, 255));
        importSalesReportButton.setText("Get  Sales Report in Table  ");
        importSalesReportButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 51, 255), 2, true));
        importSalesReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importSalesReportButtonActionPerformed(evt);
            }
        });

        salesReportTable.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        salesReportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Year", "Sales", "Profit ", "Profit Ratio", "Profit Per Order", "Sales Per Customer", "Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        salesReportTable.setRowHeight(24);
        salesReportTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salesReportTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(salesReportTable);

        showHistogramButton.setBackground(new java.awt.Color(153, 204, 255));
        showHistogramButton.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        showHistogramButton.setForeground(new java.awt.Color(102, 51, 255));
        showHistogramButton.setText("Show Histogram");
        showHistogramButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 51, 255), 2, true));
        showHistogramButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showHistogramButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 51, 255));
        jLabel1.setText("Year:");

        yearOneTextField.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        yearOneTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 51, 255), 2, true));
        yearOneTextField.setEnabled(false);

        backButton.setBackground(new java.awt.Color(153, 204, 255));
        backButton.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        backButton.setForeground(new java.awt.Color(102, 51, 255));
        backButton.setText("<<Previous Page");
        backButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 51, 255), 2, true));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 51, 255));
        jLabel2.setText("Profit:");

        profitOneTextField.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        profitOneTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 51, 255), 2, true));
        profitOneTextField.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 51, 255));
        jLabel3.setText("Year:");

        yearTwoTextField.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        yearTwoTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 51, 255), 2, true));
        yearTwoTextField.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 51, 255));
        jLabel4.setText("Profit:");

        profitTwoTextField.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        profitTwoTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 51, 255), 2, true));
        profitTwoTextField.setEnabled(false);
        profitTwoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profitTwoTextFieldActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 51, 255));
        jLabel5.setText("Year:");

        yearThreeTextField.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        yearThreeTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 51, 255), 2, true));
        yearThreeTextField.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 51, 255));
        jLabel6.setText("Profit:");

        profitThreeTextField.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        profitThreeTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 51, 255), 2, true));
        profitThreeTextField.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 51, 204));
        jLabel7.setText("Compare Profits");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(381, 381, 381)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(yearTwoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(yearThreeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(yearOneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(profitTwoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(profitOneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(33, 33, 33)
                                .addComponent(profitThreeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(489, 489, 489)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(445, 445, 445)
                        .addComponent(importSalesReportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 891, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(445, 445, 445)
                        .addComponent(showHistogramButton, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 148, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(importSalesReportButton)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(yearOneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profitOneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearTwoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(profitTwoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(yearThreeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(profitThreeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(showHistogramButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void importSalesReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importSalesReportButtonActionPerformed
        String filePath = "C:\\Final Project AED_BI_DashBoard\\bi_dashboard_final_project\\Final Project\\db4odemo\\TATA\\salesReport.txt";
        File file = new File(filePath);       
           try {
            FileReader fr = new FileReader(file);
            BufferedReader br = new BufferedReader(fr);
            
            DefaultTableModel model = (DefaultTableModel)salesReportTable.getModel();
            Object[] lines = br.lines().toArray();
            
            for(int i = 0; i < lines.length; i++){
                String[] row = lines[i].toString().split(" ");
                model.addRow(row);
            }
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ResultEngineeringPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
      
            
        
    }//GEN-LAST:event_importSalesReportButtonActionPerformed

    private void showHistogramButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showHistogramButtonActionPerformed
       try{
       String yearOne=yearOneTextField.getText();
       String yearTwo=yearTwoTextField.getText();
       String yearThree=yearThreeTextField.getText();
       
       String profitOne=profitOneTextField.getText();
       String profitTwo=profitTwoTextField.getText();
       String profitThree=profitThreeTextField.getText();
       
        DefaultCategoryDataset  dataset=new DefaultCategoryDataset();
        dataset.setValue(new Double(profitOne), "Profit", yearOne);
        dataset.setValue(new Double(profitTwo), "Profit", yearTwo);
        dataset.setValue(new Double(profitThree),"Profit", yearThree);
        
        JFreeChart chart=ChartFactory.createBarChart("Profit Report","Year","Profit", dataset, PlotOrientation.VERTICAL, false, true, false);
         CategoryPlot p=chart.getCategoryPlot();
       p.setRangeGridlinePaint(Color.black);
       ChartFrame frame=new ChartFrame("Profit Report",chart);
       frame.setVisible(true);
       frame.setSize(800,800);
       }
       catch(NumberFormatException ex){
           JOptionPane.showMessageDialog(null, "Select Rows from the table");
       }
    }//GEN-LAST:event_showHistogramButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
         userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed

    private void salesReportTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salesReportTableMouseClicked
      int i=salesReportTable.getSelectedRow();
        TableModel model=salesReportTable.getModel();
      if(i==0){        
        yearOneTextField.setText(model.getValueAt(i,0).toString());
        profitOneTextField.setText(model.getValueAt(i,2).toString());  
      }
      if((i==1)){
      yearTwoTextField.setText(model.getValueAt(i,0).toString());
      profitTwoTextField.setText(model.getValueAt(i,2).toString());
      }   
     if(i==2)
     {
    yearThreeTextField.setText(model.getValueAt(i,0).toString());
    profitThreeTextField.setText(model.getValueAt(i,2).toString());
     }
    }//GEN-LAST:event_salesReportTableMouseClicked

    private void profitTwoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profitTwoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_profitTwoTextFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton importSalesReportButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField profitOneTextField;
    private javax.swing.JTextField profitThreeTextField;
    private javax.swing.JTextField profitTwoTextField;
    private javax.swing.JTable salesReportTable;
    private javax.swing.JButton showHistogramButton;
    private javax.swing.JTextField yearOneTextField;
    private javax.swing.JTextField yearThreeTextField;
    private javax.swing.JTextField yearTwoTextField;
    // End of variables declaration//GEN-END:variables
}
