/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.TopLevelRole_Chemicals;

import Business.EcoSystem;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;
import userinterface.FinanceExecutiveRole_Chemical.FertilizersPanel;


public class ComparePanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem ecosystem;
   
    public ComparePanel(JPanel userProcessContainer,EcoSystem ecosystem) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.ecosystem=ecosystem;
        
        
    }
    
       
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        financeChemicals = new javax.swing.JTable();
        financeReportFertilizersButton = new javax.swing.JButton();
        financeReportChemicalsButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        financeReportFertilizers1 = new javax.swing.JTable();
        financeReporBioFuelsButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        financeReportBiofuels = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        yearChemTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        totalIncomeFerti = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        yearFerti = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        totalIncomeChem = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        yearBioFuels = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        totalIncomeBio = new javax.swing.JTextField();
        compareButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 204, 255));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 51, 255), 2, true));

        financeChemicals.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        financeChemicals.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Year", "Total Comprehensive Income", "Organic Growth", "Profit"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        financeChemicals.setRowHeight(22);
        financeChemicals.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                financeChemicalsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(financeChemicals);
        if (financeChemicals.getColumnModel().getColumnCount() > 0) {
            financeChemicals.getColumnModel().getColumn(0).setResizable(false);
            financeChemicals.getColumnModel().getColumn(1).setResizable(false);
            financeChemicals.getColumnModel().getColumn(2).setResizable(false);
            financeChemicals.getColumnModel().getColumn(3).setResizable(false);
        }

        financeReportFertilizersButton.setBackground(new java.awt.Color(153, 204, 255));
        financeReportFertilizersButton.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        financeReportFertilizersButton.setForeground(new java.awt.Color(102, 51, 204));
        financeReportFertilizersButton.setText("Get Finance Report of Fertilizers");
        financeReportFertilizersButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 51, 255), 2, true));
        financeReportFertilizersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                financeReportFertilizersButtonActionPerformed(evt);
            }
        });

        financeReportChemicalsButton.setBackground(new java.awt.Color(153, 204, 255));
        financeReportChemicalsButton.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        financeReportChemicalsButton.setForeground(new java.awt.Color(102, 51, 255));
        financeReportChemicalsButton.setText("Get Finance Report of Chemicals");
        financeReportChemicalsButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 51, 255), 2, true));
        financeReportChemicalsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                financeReportChemicalsButtonActionPerformed(evt);
            }
        });

        financeReportFertilizers1.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        financeReportFertilizers1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Year", "Total Comprehensive Income", "Organic Growth", "Profit"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        financeReportFertilizers1.setRowHeight(24);
        financeReportFertilizers1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                financeReportFertilizers1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(financeReportFertilizers1);
        if (financeReportFertilizers1.getColumnModel().getColumnCount() > 0) {
            financeReportFertilizers1.getColumnModel().getColumn(0).setResizable(false);
            financeReportFertilizers1.getColumnModel().getColumn(1).setResizable(false);
            financeReportFertilizers1.getColumnModel().getColumn(2).setResizable(false);
            financeReportFertilizers1.getColumnModel().getColumn(3).setResizable(false);
        }

        financeReporBioFuelsButton.setBackground(new java.awt.Color(153, 204, 255));
        financeReporBioFuelsButton.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        financeReporBioFuelsButton.setForeground(new java.awt.Color(102, 51, 255));
        financeReporBioFuelsButton.setText("Get Finance Report of BioFuels");
        financeReporBioFuelsButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 51, 255), 2, true));
        financeReporBioFuelsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                financeReporBioFuelsButtonActionPerformed(evt);
            }
        });

        financeReportBiofuels.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        financeReportBiofuels.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Year", "Total Comprehensive Income", "Organic Growth", "Profit"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        financeReportBiofuels.setRowHeight(24);
        financeReportBiofuels.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                financeReportBiofuelsMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(financeReportBiofuels);
        if (financeReportBiofuels.getColumnModel().getColumnCount() > 0) {
            financeReportBiofuels.getColumnModel().getColumn(0).setResizable(false);
            financeReportBiofuels.getColumnModel().getColumn(1).setResizable(false);
            financeReportBiofuels.getColumnModel().getColumn(2).setResizable(false);
            financeReportBiofuels.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 51, 204));
        jLabel1.setText("Compare Total Comprehensive Income");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 51, 204));
        jLabel2.setText("Year :");

        yearChemTextField.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        yearChemTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 51, 255), 2, true));
        yearChemTextField.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 51, 204));
        jLabel3.setText("Total Comprehensive Income:");

        totalIncomeFerti.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        totalIncomeFerti.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 51, 255), 2, true));
        totalIncomeFerti.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 51, 204));
        jLabel4.setText("Chemicals");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 51, 204));
        jLabel5.setText("Fertilizers");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 51, 204));
        jLabel6.setText("Year:");

        yearFerti.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        yearFerti.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 51, 255), 2, true));
        yearFerti.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 51, 204));
        jLabel7.setText("Total Comprehensive Income:");

        totalIncomeChem.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        totalIncomeChem.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 51, 255), 2, true));
        totalIncomeChem.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 51, 204));
        jLabel8.setText("Biofuels:");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 51, 204));
        jLabel9.setText("Year:");

        yearBioFuels.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        yearBioFuels.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 51, 255), 2, true));
        yearBioFuels.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 51, 204));
        jLabel10.setText("Total Comprehensive Income:");

        totalIncomeBio.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        totalIncomeBio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 51, 255), 2, true));
        totalIncomeBio.setEnabled(false);

        compareButton.setBackground(new java.awt.Color(153, 204, 255));
        compareButton.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        compareButton.setForeground(new java.awt.Color(102, 51, 255));
        compareButton.setText("Compare ");
        compareButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 51, 255), 2, true));
        compareButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compareButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(financeReportChemicalsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(294, 294, 294)
                        .addComponent(financeReportFertilizersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(financeReporBioFuelsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(427, 427, 427)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(149, 149, 149)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(157, 157, 157)
                                        .addComponent(jLabel8)))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(yearChemTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(88, 88, 88)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(totalIncomeChem, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(yearFerti, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(yearBioFuels, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(84, 84, 84)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel10)
                                                .addGap(18, 18, 18)
                                                .addComponent(totalIncomeBio))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(18, 18, 18)
                                                .addComponent(totalIncomeFerti))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(393, 393, 393)
                                .addComponent(compareButton, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(887, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(financeReportChemicalsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(financeReportFertilizersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(financeReporBioFuelsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(3, 3, 3)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(yearChemTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(totalIncomeChem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(yearFerti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(totalIncomeFerti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(yearBioFuels, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(totalIncomeBio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(compareButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(307, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void financeReportFertilizersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_financeReportFertilizersButtonActionPerformed
        DefaultTableModel table = (DefaultTableModel) financeReportFertilizers1.getModel();
        String[] row1 = {"2015","800","80","8000"};
        String[] row2 = {"2016","2100","90","9800"};
        String[] row3 = {"2017","1700","25","7200"};
        //String[] row4 = {"","","",""};
        table.addRow(row1);
        table.addRow(row2);
        table.addRow(row3);
    }//GEN-LAST:event_financeReportFertilizersButtonActionPerformed

    private void financeReportChemicalsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_financeReportChemicalsButtonActionPerformed
        DefaultTableModel table = (DefaultTableModel) financeChemicals.getModel();
        String[] row1 = {"2015","1200","20","1500"};
        String[] row2 = {"2016","1500","40","1800"};
        String[] row3 = {"2017","900","30","1330"};
        //String[] row4 = {"","","",""};
        table.addRow(row1);
        table.addRow(row2);
        table.addRow(row3);
    }//GEN-LAST:event_financeReportChemicalsButtonActionPerformed

    private void financeReporBioFuelsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_financeReporBioFuelsButtonActionPerformed
        DefaultTableModel table = (DefaultTableModel) financeReportBiofuels.getModel();
        String[] row1 = {"2015","4500","56","8900"};
        String[] row2 = {"2016","6700","37","1100"};
        String[] row3 = {"2017","3300","83","7700"};
        //String[] row4 = {"","","",""};
        table.addRow(row1);
        table.addRow(row2);
        table.addRow(row3);
    }//GEN-LAST:event_financeReporBioFuelsButtonActionPerformed

    private void financeChemicalsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_financeChemicalsMouseClicked
        int i=financeChemicals.getSelectedRow();
        TableModel model=financeChemicals.getModel();
        if(i==0){
           yearChemTextField.setText(model.getValueAt(i,0).toString());
        totalIncomeChem.setText(model.getValueAt(i,1).toString());
        }
        if(i==1){
           yearChemTextField.setText(model.getValueAt(i,0).toString());
        totalIncomeChem.setText(model.getValueAt(i,1).toString());
        }
        if(i==2){
           yearChemTextField.setText(model.getValueAt(i,0).toString());
        totalIncomeChem.setText(model.getValueAt(i,1).toString());
        }
            
    }//GEN-LAST:event_financeChemicalsMouseClicked

    private void financeReportFertilizers1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_financeReportFertilizers1MouseClicked
        int i=financeReportFertilizers1.getSelectedRow();
        TableModel model=financeReportFertilizers1.getModel();
        if(i==0){
           yearFerti.setText(model.getValueAt(i,0).toString());
        totalIncomeFerti.setText(model.getValueAt(i,1).toString());
        }
        if(i==1){
           yearFerti.setText(model.getValueAt(i,0).toString());
        totalIncomeFerti.setText(model.getValueAt(i,1).toString());
        }
        if(i==2){
           yearFerti.setText(model.getValueAt(i,0).toString());
        totalIncomeFerti.setText(model.getValueAt(i,1).toString());
        }
    }//GEN-LAST:event_financeReportFertilizers1MouseClicked

    private void financeReportBiofuelsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_financeReportBiofuelsMouseClicked
         int i=financeReportBiofuels.getSelectedRow();
        TableModel model=financeReportBiofuels.getModel();
        if(i==0){
           yearBioFuels.setText(model.getValueAt(i,0).toString());
        totalIncomeBio.setText(model.getValueAt(i,1).toString());
        }
        if(i==1){
           yearBioFuels.setText(model.getValueAt(i,0).toString());
        totalIncomeBio.setText(model.getValueAt(i,1).toString());
        }
        if(i==2){
           yearBioFuels.setText(model.getValueAt(i,0).toString());
        totalIncomeBio.setText(model.getValueAt(i,1).toString());
        }
    }//GEN-LAST:event_financeReportBiofuelsMouseClicked

    private void compareButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compareButtonActionPerformed
       String yearChem=yearChemTextField.getText();
       String yearFert=yearFerti.getText();
       String yearBio=yearBioFuels.getText();
       
       String totalIncomeChemi=totalIncomeChem.getText();
       String totalIncomeFert=totalIncomeFerti.getText();
       String totalIncomeBioF=totalIncomeBio.getText();
        DefaultPieDataset  pieDataset=new DefaultPieDataset();
        
        if(yearChem.equals(yearFert) &&(yearFert.equals(yearBio)) &&(yearBio.equals(yearChem))){
            
        
       pieDataset.setValue("Chemicals", new Integer(totalIncomeChemi));
       pieDataset.setValue("Fertilizers", new Integer(totalIncomeFert));
       pieDataset.setValue("Biofuels", new Integer(totalIncomeBioF));      
        JFreeChart chart =ChartFactory.createPieChart3D("Comparison Results-Total Income:"+yearChem, pieDataset,true,true,true);
        PiePlot p=(PiePlot)chart.getPlot();
        ChartFrame frame=new ChartFrame("Total Comprehensive Income-"+yearChem,chart);
        
        frame.setVisible(true);
        frame.setSize(450,500);    
        }
        else{
       
           JOptionPane.showMessageDialog(null, "For Comparison Years Should be Same!");
        }
    }//GEN-LAST:event_compareButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton compareButton;
    private javax.swing.JTable financeChemicals;
    private javax.swing.JButton financeReporBioFuelsButton;
    private javax.swing.JTable financeReportBiofuels;
    private javax.swing.JButton financeReportChemicalsButton;
    private javax.swing.JTable financeReportFertilizers1;
    private javax.swing.JButton financeReportFertilizersButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField totalIncomeBio;
    private javax.swing.JTextField totalIncomeChem;
    private javax.swing.JTextField totalIncomeFerti;
    private javax.swing.JTextField yearBioFuels;
    private javax.swing.JTextField yearChemTextField;
    private javax.swing.JTextField yearFerti;
    // End of variables declaration//GEN-END:variables
}
