/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.TopLevelRole_Chemicals;

import Business.EcoSystem;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author msneh
 */
public class FertilizersFinanceReport extends javax.swing.JPanel {

   private JPanel userProcessContainer;
   private EcoSystem ecosystem;
    public FertilizersFinanceReport(JPanel userProcessContainer,EcoSystem ecosystem) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.ecosystem=ecosystem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        financeReportFertilizersButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        financeReportChemicals = new javax.swing.JTable();

        setBackground(new java.awt.Color(153, 204, 255));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 51, 255), 2, true));

        financeReportFertilizersButton.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        financeReportFertilizersButton.setForeground(new java.awt.Color(102, 51, 255));
        financeReportFertilizersButton.setText("Get Finance Report of Fertilizers");
        financeReportFertilizersButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 51, 255), 2, true));
        financeReportFertilizersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                financeReportFertilizersButtonActionPerformed(evt);
            }
        });

        financeReportChemicals.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        financeReportChemicals.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Year", "Total Comprehensive Income", "Organic Growth", "Profit"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        financeReportChemicals.setRowHeight(22);
        jScrollPane1.setViewportView(financeReportChemicals);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 920, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
            .addGroup(layout.createSequentialGroup()
                .addGap(388, 388, 388)
                .addComponent(financeReportFertilizersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(financeReportFertilizersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(395, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void financeReportFertilizersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_financeReportFertilizersButtonActionPerformed
        DefaultTableModel table = (DefaultTableModel) financeReportChemicals.getModel();
        String[] row1 = {"2015","800","80","8000"};
        String[] row2 = {"2016","2100","90","9800"};
        String[] row3 = {"2017","1700","25","7200"};
        //String[] row4 = {"","","",""};
        table.addRow(row1);
        table.addRow(row2);
        table.addRow(row3);
    }//GEN-LAST:event_financeReportFertilizersButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable financeReportChemicals;
    private javax.swing.JButton financeReportFertilizersButton;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
