/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SalesExecutiveRole_Engineering;

import Business.EcoSystem;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author msneh
 */
public class CommercialVehiclesPanel extends javax.swing.JPanel {

   //private JPanel rightPanelSales;
   private EcoSystem ecosystem;
   private JPanel userContainer;
  
    public CommercialVehiclesPanel(JPanel userContainer,EcoSystem ecosystem) {
        initComponents();
        //this.rightPanelSales=rightPanelSales;
        this.ecosystem=ecosystem;
        this.userContainer=userContainer;
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tataNanoButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tataTiagoButton = new javax.swing.JButton();
        tataZestButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 204, 255));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 51, 255), 2, true));

        tataNanoButton.setBackground(new java.awt.Color(153, 204, 255));
        tataNanoButton.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        tataNanoButton.setForeground(new java.awt.Color(102, 51, 255));
        tataNanoButton.setText("TATA Nano");
        tataNanoButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 51, 255), 2, true));
        tataNanoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tataNanoButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 51, 255));
        jLabel1.setText("TATA Motors");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 51, 255));
        jLabel3.setText("Commercial Vehicles");

        tataTiagoButton.setBackground(new java.awt.Color(153, 204, 255));
        tataTiagoButton.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        tataTiagoButton.setForeground(new java.awt.Color(102, 51, 255));
        tataTiagoButton.setText("TATA Tiago");
        tataTiagoButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 51, 255), 2, true));
        tataTiagoButton.setEnabled(false);
        tataTiagoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tataTiagoButtonActionPerformed(evt);
            }
        });

        tataZestButton.setBackground(new java.awt.Color(153, 204, 255));
        tataZestButton.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        tataZestButton.setForeground(new java.awt.Color(102, 51, 255));
        tataZestButton.setText("TATA Zest");
        tataZestButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 51, 255), 2, true));
        tataZestButton.setEnabled(false);
        tataZestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tataZestButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(449, 449, 449)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tataTiagoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tataNanoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tataZestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(466, 466, 466)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel1)))))
                .addContainerGap(478, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(77, 77, 77)
                .addComponent(jLabel3)
                .addGap(35, 35, 35)
                .addComponent(tataNanoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tataTiagoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tataZestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(340, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tataNanoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tataNanoButtonActionPerformed
         TataNanoPanel nanoPanel=new TataNanoPanel(userContainer, ecosystem);
        userContainer.add("nanoPanel",nanoPanel);
        CardLayout layout=(CardLayout)userContainer.getLayout();
        layout.next(userContainer);
    }//GEN-LAST:event_tataNanoButtonActionPerformed

    private void tataZestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tataZestButtonActionPerformed
       TataZestPanel zestPanel=new TataZestPanel(userContainer, ecosystem);
        userContainer.add("zestPanel",zestPanel);
        CardLayout layout=(CardLayout)userContainer.getLayout();
        layout.next(userContainer);
        
        
    }//GEN-LAST:event_tataZestButtonActionPerformed

    private void tataTiagoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tataTiagoButtonActionPerformed
        
    }//GEN-LAST:event_tataTiagoButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton tataNanoButton;
    private javax.swing.JButton tataTiagoButton;
    private javax.swing.JButton tataZestButton;
    // End of variables declaration//GEN-END:variables
}
