/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.FinanceExecutiveRole_Chemical;

import Business.EcoSystem;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author msneh
 */
public class ChemicalProductsPanel extends javax.swing.JPanel {

   private JPanel userProcessContainer;
   private EcoSystem ecosystem;
    public ChemicalProductsPanel(JPanel userProcessContainer,EcoSystem ecosystem) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.ecosystem=ecosystem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        chemicalsButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        fertilizersButton = new javax.swing.JButton();
        bioFuelsButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        bottomPanel = new javax.swing.JPanel();

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 51, 255), 2, true));

        chemicalsButton.setBackground(new java.awt.Color(153, 204, 255));
        chemicalsButton.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        chemicalsButton.setForeground(new java.awt.Color(102, 51, 255));
        chemicalsButton.setText("Chemicals");
        chemicalsButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 51, 255), 2, true));
        chemicalsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chemicalsButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 51, 255));
        jLabel1.setText("Product Range:");

        fertilizersButton.setBackground(new java.awt.Color(153, 204, 255));
        fertilizersButton.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        fertilizersButton.setForeground(new java.awt.Color(102, 51, 255));
        fertilizersButton.setText("Fertilizers");
        fertilizersButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 51, 255), 2, true));
        fertilizersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fertilizersButtonActionPerformed(evt);
            }
        });

        bioFuelsButton.setBackground(new java.awt.Color(153, 204, 255));
        bioFuelsButton.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        bioFuelsButton.setForeground(new java.awt.Color(102, 51, 255));
        bioFuelsButton.setText("Biofuels");
        bioFuelsButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 51, 255), 2, true));
        bioFuelsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bioFuelsButtonActionPerformed(evt);
            }
        });

        backButton.setBackground(new java.awt.Color(153, 204, 255));
        backButton.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        backButton.setForeground(new java.awt.Color(102, 51, 255));
        backButton.setText("<<Previous Page");
        backButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 51, 255), 2, true));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addGap(63, 63, 63)
                .addComponent(chemicalsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fertilizersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bioFuelsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(chemicalsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fertilizersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bioFuelsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );

        jSplitPane1.setTopComponent(jPanel1);

        bottomPanel.setBackground(new java.awt.Color(153, 204, 255));
        bottomPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 51, 255), 2, true));
        bottomPanel.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(bottomPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 749, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void chemicalsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chemicalsButtonActionPerformed
        ChemicalsRangePanel chemicalRange = new ChemicalsRangePanel(bottomPanel, ecosystem);
        CardLayout cardLayout = (CardLayout)bottomPanel.getLayout();
        bottomPanel.add("chemRange",chemicalRange);
        cardLayout.next(bottomPanel);
    }//GEN-LAST:event_chemicalsButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed

    private void fertilizersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fertilizersButtonActionPerformed
        FertilizersPanel fertiRange = new FertilizersPanel(bottomPanel, ecosystem);
        CardLayout cardLayout = (CardLayout)bottomPanel.getLayout();
        bottomPanel.add("fertiRange",fertiRange);
        cardLayout.next(bottomPanel);
    }//GEN-LAST:event_fertilizersButtonActionPerformed

    private void bioFuelsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bioFuelsButtonActionPerformed
         BioFuelsPanel bioRange = new BioFuelsPanel(bottomPanel, ecosystem);
        CardLayout cardLayout = (CardLayout)bottomPanel.getLayout();
        bottomPanel.add("bioRange",bioRange);
        cardLayout.next(bottomPanel);
    }//GEN-LAST:event_bioFuelsButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton bioFuelsButton;
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JButton chemicalsButton;
    private javax.swing.JButton fertilizersButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
