/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.FinanceExecutiveRole_Chemical;

import Business.EcoSystem;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


public class BioFuelsPanel extends javax.swing.JPanel {

    private JPanel bottomPanel;
    private EcoSystem ecosystem;
    public BioFuelsPanel(JPanel bottomPanel,EcoSystem ecosystem) {
        initComponents();
        this.bottomPanel=bottomPanel;
        this.ecosystem=ecosystem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        year = new javax.swing.JLabel();
        totalIncome = new javax.swing.JLabel();
        organicGrowth = new javax.swing.JLabel();
        profitLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        year2015Label = new javax.swing.JLabel();
        totalIncome2015Chemicals = new javax.swing.JLabel();
        growth2015Chemicals = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        profit2015Chemicals = new javax.swing.JLabel();
        year2016Label = new javax.swing.JLabel();
        totalIncome2016Chemicals = new javax.swing.JLabel();
        growth2016Chemicals = new javax.swing.JLabel();
        profit2016Chemicals = new javax.swing.JLabel();
        year2017Chemicals = new javax.swing.JLabel();
        totalIncome2017Chemicals = new javax.swing.JLabel();
        growth2017Chemicals = new javax.swing.JLabel();
        profit2017chemicals = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 51, 255), 2, true));
        jPanel1.setForeground(new java.awt.Color(102, 51, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 51, 255));
        jLabel1.setText("Finance Statement :Biofuels");

        year.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        year.setForeground(new java.awt.Color(102, 51, 255));
        year.setText("Year");

        totalIncome.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        totalIncome.setForeground(new java.awt.Color(102, 51, 255));
        totalIncome.setText("Total Comprehensive  Income");

        organicGrowth.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        organicGrowth.setForeground(new java.awt.Color(102, 51, 255));
        organicGrowth.setText("Organic Growth");

        profitLabel.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        profitLabel.setForeground(new java.awt.Color(102, 51, 255));
        profitLabel.setText("Profit");

        year2015Label.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        year2015Label.setForeground(new java.awt.Color(102, 51, 255));
        year2015Label.setText("2015");

        totalIncome2015Chemicals.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        totalIncome2015Chemicals.setForeground(new java.awt.Color(102, 51, 255));
        totalIncome2015Chemicals.setText("4500");

        growth2015Chemicals.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        growth2015Chemicals.setForeground(new java.awt.Color(102, 51, 255));
        growth2015Chemicals.setText("56");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 19)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 51, 255));
        jLabel6.setText("(in percentage)");

        profit2015Chemicals.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        profit2015Chemicals.setForeground(new java.awt.Color(102, 51, 255));
        profit2015Chemicals.setText("8900");

        year2016Label.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        year2016Label.setForeground(new java.awt.Color(102, 51, 255));
        year2016Label.setText("2016");

        totalIncome2016Chemicals.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        totalIncome2016Chemicals.setForeground(new java.awt.Color(102, 51, 255));
        totalIncome2016Chemicals.setText("6700");

        growth2016Chemicals.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        growth2016Chemicals.setForeground(new java.awt.Color(102, 51, 255));
        growth2016Chemicals.setText("37");

        profit2016Chemicals.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        profit2016Chemicals.setForeground(new java.awt.Color(102, 51, 255));
        profit2016Chemicals.setText("1100");

        year2017Chemicals.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        year2017Chemicals.setForeground(new java.awt.Color(102, 51, 255));
        year2017Chemicals.setText("2017");

        totalIncome2017Chemicals.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        totalIncome2017Chemicals.setForeground(new java.awt.Color(102, 51, 255));
        totalIncome2017Chemicals.setText("3300");

        growth2017Chemicals.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        growth2017Chemicals.setForeground(new java.awt.Color(102, 51, 255));
        growth2017Chemicals.setText("83");

        profit2017chemicals.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        profit2017chemicals.setForeground(new java.awt.Color(102, 51, 255));
        profit2017chemicals.setText("7700");

        jButton1.setBackground(new java.awt.Color(153, 204, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 51, 255));
        jButton1.setText("Save Report as Text File");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 51, 255), 2, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(year)
                                    .addComponent(year2015Label))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(133, 133, 133)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(totalIncome2015Chemicals)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(totalIncome2016Chemicals)
                                            .addComponent(totalIncome2017Chemicals))
                                        .addGap(130, 130, 130)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(growth2015Chemicals)
                                            .addComponent(growth2016Chemicals)
                                            .addComponent(growth2017Chemicals))
                                        .addGap(280, 280, 280)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(profit2016Chemicals)
                                            .addComponent(profit2017chemicals)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(67, 67, 67)
                                        .addComponent(totalIncome)
                                        .addGap(34, 34, 34)
                                        .addComponent(organicGrowth)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6)
                                        .addGap(28, 28, 28)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(profit2015Chemicals)
                                            .addComponent(profitLabel)))))
                            .addComponent(year2016Label)
                            .addComponent(year2017Chemicals)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(445, 445, 445)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(491, 491, 491)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(210, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel1)
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(year)
                    .addComponent(totalIncome)
                    .addComponent(organicGrowth)
                    .addComponent(jLabel6)
                    .addComponent(profitLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(year2015Label)
                            .addComponent(totalIncome2015Chemicals)
                            .addComponent(growth2015Chemicals)
                            .addComponent(profit2015Chemicals)))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(year2016Label)
                    .addComponent(totalIncome2016Chemicals)
                    .addComponent(growth2016Chemicals)
                    .addComponent(profit2016Chemicals))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(year2017Chemicals)
                    .addComponent(totalIncome2017Chemicals)
                    .addComponent(growth2017Chemicals)
                    .addComponent(profit2017chemicals))
                .addGap(90, 90, 90)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(338, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String filePath="C:\\Final Project AED_BI_DashBoard\\bi_dashboard_final_project\\Final Project\\db4odemo\\TATA\\BioFuelsReport.txt";
        File file = new File(filePath);
        try {
            FileWriter fw = new FileWriter(file);
            BufferedWriter bw = new BufferedWriter(fw);
            PrintWriter pw=new PrintWriter(bw);
            bw.write(year.getText(),0,4);
            bw.write("\t",0,1);
            bw.write(totalIncome.getText(),0,27);
            bw.write("\t",0,1);
            bw.write(organicGrowth.getText(),0,14);
            bw.write("\t\t",0,2);
            bw.write(profitLabel.getText(),0,6);

            bw.newLine();

            bw.write(year2015Label.getText(),0,4);
            bw.write("\t\t",0,2);
            bw.write(totalIncome2015Chemicals.getText(),0,4);
            bw.write("\t\t\t\t",0,4);
            bw.write(growth2015Chemicals.getText(),0,2);
            bw.write("\t\t",0,2);
            bw.write(profit2015Chemicals.getText(),0,4);
            bw.write("\t\t",0,2);

            bw.newLine();

            bw.write(year2016Label.getText(),0,4);
            bw.write("\t\t",0,2);
            bw.write(totalIncome2016Chemicals.getText(),0,4);
            bw.write("\t\t\t\t",0,4);
            bw.write(growth2016Chemicals.getText(),0,2);
            bw.write("\t\t",0,2);
            bw.write(profit2016Chemicals.getText(),0,4);
            bw.write("\t\t",0,2);

            bw.newLine();

            bw.write(year2017Chemicals.getText(),0,4);
            bw.write("\t\t",0,2);
            bw.write(totalIncome2016Chemicals.getText(),0,4);
            bw.write("\t\t\t\t",0,4);
            bw.write(growth2017Chemicals.getText(),0,2);
            bw.write("\t\t",0,2);
            bw.write(profit2017chemicals.getText(),0,4);
            bw.write("\t\t",0,2);

            bw.close();
            fw.close();
            pw.close();

        }
        catch(IOException ex){
            Logger.getLogger(ChemicalsRangePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null, "Saved as Text File!");
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel growth2015Chemicals;
    private javax.swing.JLabel growth2016Chemicals;
    private javax.swing.JLabel growth2017Chemicals;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel organicGrowth;
    private javax.swing.JLabel profit2015Chemicals;
    private javax.swing.JLabel profit2016Chemicals;
    private javax.swing.JLabel profit2017chemicals;
    private javax.swing.JLabel profitLabel;
    private javax.swing.JLabel totalIncome;
    private javax.swing.JLabel totalIncome2015Chemicals;
    private javax.swing.JLabel totalIncome2016Chemicals;
    private javax.swing.JLabel totalIncome2017Chemicals;
    private javax.swing.JLabel year;
    private javax.swing.JLabel year2015Label;
    private javax.swing.JLabel year2016Label;
    private javax.swing.JLabel year2017Chemicals;
    // End of variables declaration//GEN-END:variables
}
